server:
  port: 8080
spring:
  thymeleaf:
    cache: false
  datasource:
    username: root
    password: lxl123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/myblog?useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true
